### ISSUE TITLE
Unknown plugin error

### ISSUE THREAD

**Issue by Codecomp** [Pageclip/valid-form#3]
I was trying this out with my project and got the following error, Never had any issues previously  like this with gulp and babelify in this framework so unsure if my environment or the module.

`ReferenceError: Unknown plugin "transform-runtime" specified in "[repo]/node_modules/@pageclip/valid-form/.babelrc" at 0, attempted to resolve relative to "[repo]/node_modules/@pageclip/valid-form" while parsing file: [repo]/node_modules/@pageclip/valid-form/index.js
    at [repo]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins ([repo]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions ([repo]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init ([repo]/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions ([repo]/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File ([repo]/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform ([repo]/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at Babelify._flush ([repo]/node_modules/babelify/index.js:26:24)
    at Babelify.prefinish (_stream_transform.js:137:10)
    at emitNone (events.js:105:13)
    at Babelify.emit (events.js:207:7)
    at prefinish (_stream_writable.js:576:14)
    at finishMaybe (_stream_writable.js:584:5)
    at endWritable (_stream_writable.js:595:3)
    at Babelify.Writable.end (_stream_writable.js:546:5)

**Comment by benogle** [comment]
Can you try installing `babel-plugin-transform-runtime` to devDependencies? I will see if I can remove the dependency, but for now that should be the fix.
